[target.'cfg(all())']
rustflags = [
    "-Wclippy::all",
    "-Wclippy::pedantic",
    "-Wclippy::nursery",
    "-Aclippy::must_use_candidate",
    "-Aclippy::missing_errors_doc",
    "-Aclippy::missing_panics_doc",
    "-Aclippy::cast_possible_truncation",
    "-Aclippy::cast_possible_wrap",
    "-Aclippy::needless_pass_by_value",
]
